sudo: false
dist: trusty
language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 3.3
  - 2.7
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
#install: pip install nose
# command to run tests, e.g. python setup.py test
script:  nosetests

addons:
  apt:
    packages:
    - hicolor-icon-theme  # A test tries to parse the theme file
